#!/usr/bin/env python

import sys
import time
import pdb
import itertools
import re

import paramiko
import subprocess

import topology2 as topology
import config2 as config
from elascale_setup import config_hosts_elascale

import novaclient.v1_1.client as nclient
import novaclient.v1_1.shell as nshell
from quantumclient.v2_0 import client as qclient
from quantumclient.quantum import v2_0 as quantumv20
from prettytable import PrettyTable

def add_secrules(nova, secgroup):
    """
    Creates secgroup
    parameters
        nova:-nova client object
    """
    #TODO: Check rule does not exist, use secgroup.rules or nova.security_group_rules.find()
    rules = [("TCP", 22, 22), ("UDP", 4789, 4789), ("ICMP", -1, 255)]
    for rule in rules:
        try:
            nova.security_group_rules.create(secgroup.id, rule[0], rule[1], rule[2], "10.0.0.0/8")
        except Exception as e:
            if "rule already exists" not in e.message:
                print e.message

def create_node(node, node_name, region, flavor, nova, nics):
    print "Creating " + node_name

    #Get params
    user_name =  node.get('vm_user_name', config.vm_user_name)
    server_name = node.get('server', None)
    region_name = region
    instance_name = node.get('name', config.instance_prefix + node_name)
    #Search for image and flavor
    flavor = nshell._find_flavor(nova, node.get('flavor', flavor))
    image = nshell._find_image(nova, node.get('image', config.image_name))

    vm=nova.servers.create(instance_name, image, flavor, key_name=config.key_name,
        security_groups=seclist, scheduler_hints={"force_hosts":server_name}, nics=nics)
    return {"vm":vm, "status": 1, "name": node_name,
        "instance_name": instance_name, "user_name": user_name }

def pretty_print(nodes):
    for node_name, node in nodes.items():
        n = node["vm"]
        ptable = PrettyTable(["Property", "Value"])
        ptable.add_row(["Node name",  node["name"]])
        ptable.add_row(["VM name",    node["instance_name"]])
        ptable.add_row(["Network ID", node["network_id"]])
        ptable.add_row(["VM ID", n.id])
        ptable.add_row(["Host",str(getattr(n, "OS-EXT-SRV-ATTR:host"))])
        ptable.add_row(["Instance Name",str(getattr(n, "OS-EXT-SRV-ATTR:instance_name"))])
        ptable.add_row(["Internal IP addr", node["ip_addr"]])
        print ptable

def check_server_status(nodes):
    """
    Busy loops until each server either is up or fails

    VM status:
       -1-error
        0-no op
        1-build initiated
        2-ip address allocated
    """
    while True:
        in_progress = filter(lambda h: h["status"] == 1, nodes.values())
        if len(in_progress) == 0: return
        print "Waiting for {} servers".format(len(in_progress))

        for node in in_progress:
            n = node["vm"]
            n.get()
            if n.status == "ERROR":
                node["status"] = -1
                print "{} completed with error".format(node["name"])
            elif n.status == "ACTIVE":
                node["status"] = 2
                vm_net, vm_ip = n.networks.popitem()
                node["ip_addr"] = vm_ip[0]
                node["net"] = vm_net
                print "{} completed successfully".format(node["name"])
            time.sleep(6)

def error_check():
    #Check 1: Private key file exists
    try:
        with open(private_key_file, 'r') as private_key:
            pass
    except:
        print "Unable to open private key file at: '{}'".format(private_key_file)
        sys.exit(1)

def sanity_test(nodes):
    for n in nodes.values():
        #VM may not be up, loop until ping successful
        while True:
            print "Pinging {} at {}".format(n["name"], n["ip_addr"])
            try:
                output=subprocess.check_output(['ping', '-c 3', n["ip_addr"] ])
                print output
                break
            except Exception as e:
                print e
                print "Unable to ping. Trying again...."
                time.sleep(5)

        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        while True:
            try:
                ssh.connect(n["ip_addr"], username=n["user_name"], key_filename=config.private_key_file)
                break
            except Exception as e:
                print e
                print "Unable to connect. Trying again...."
                time.sleep(5)

        time.sleep(3)

        stdin, stdout, stderr = ssh.exec_command("uptime")
        stdin.close()
        out1=stdout.readlines()
        print "uptime output is: %s" % (''.join(out1))
        time.sleep(1)

        stdin, stdout, stderr = ssh.exec_command("ping -c2 www.google.ca")
        stdin.close()
        out2=stdout.readlines()
        print "ping output is: %s" % (''.join(out2))
        ssh.close()

def _get_vm_id(node):
    vm_id = 0
    #Extract switch number
    if node.lower().startswith('sw'):
       vm_id = int(node.lower()[2:]) * 100
    #Extract host number
    elif node.lower().startswith('h'):
       vm_id = int(node.lower()[1:])
    return vm_id

def _get_vni(node1, node2):
    #Returns same VNI between two VMs
    vid1 = _get_vm_id(node1)
    vid2 = _get_vm_id(node2)

    vni =  max(vid1, vid2) + min(vid1, vid2)
    #print "%s --> %s : %s" %(node1, node2, vni)
    return vni

# Function used to ssh into VM and adds hostname to /etc/hosts
# Param: ssh variable used to connect
def add_hostname(ssh):

    stdin, stdout, stderr = ssh.exec_command("cat /proc/sys/kernel/hostname",timeout=25)
    hostname = (stdout.read()).strip()

    command = 'sudo sed -i "s/127.0.0.1 .*/127.0.0.1 localhost '+hostname+'/g" /etc/hosts'
    verify_command = "cat /etc/hosts"
    keyword_search = hostname
    execute_and_verify(ssh, command, verify_command, keyword_search)

# Executes command using Paramiko ssh client and verifies if it successfully executed it
# Params:
#    shell: The ssh variable used to connect to remote host
#    command: The command to execute
#    verify_command: Specify whether 'ovs' or 'ifconfig'
#    keyword_searcch: search this keyword inside verify_command output
def execute_and_verify(shell, command, verify_command, keyword_search):
    while True:
        try:
            shell.exec_command(command, timeout=25)
            time.sleep(1)

            if verify_command == "ovs" or verify_command == "ifconfig":
                verify = "sudo ovs-vsctl show && sudo ifconfig -a"
            else:
                verify = verify_command
            """
            if verify_command == "ovs":
                verify = "sudo ovs-vsctl show"
            elif verify_command == "ifconfig":
                verify = "sudo ifconfig"
            else:
                verify = verify_command
            """
            stdin, stdout, stderr = shell.exec_command(verify,timeout=25)
            output = stdout.read()

            if keyword_search in output:
                print output
                print "successfully executed (above) command"
                break
            else:
                print "Not executed yet. Trying again..."
                time.sleep(5)
        except Exception as e:
            print e
            print "Unable to execute command. Trying again...."
            time.sleep(5)

def setup_switches(hosts_dict, switches_dict):
    #Iterate over all switches
    for sw_name, sw_dict in switches_dict.items():
        sw_prop_map = topology.switches[sw_name] #The properties of the switch
        sw_topo_map = topology.topology[sw_name] #The list of interconnections
        #print "setting up {}".format(sw_name)
        print("*** SETUP SWITCH: %s ***" %sw_name)

        #ssh to VM
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(sw_dict["ip_addr"], username=sw_dict["user_name"], key_filename=config.private_key_file)
        time.sleep(3)

        # Add hostname to VM, such that it does not annoy with 'Unable to ...' error
        add_hostname(ssh)

        # run the ovs commands
        bridge_name = sw_prop_map['bridge_name']

        command = "sudo ovs-vsctl add-br %s" % bridge_name
        print("## OVS-COMMAND: %s" %command)
        execute_and_verify(ssh, command, "ovs", bridge_name)

        command = "sudo ovs-vsctl set Bridge %s rotocols=OpenFlow13" % bridge_name
        print("## OVS-COMMAND: %s" %command)
        execute_and_verify(ssh, command, "ovs", bridge_name)

        #Attach controller
        #Default for a OVS switch, is standalone mode
        contr_addr = sw_prop_map.get('contr_addr', topology.contr_addr)
        if contr_addr :

            command = "sudo ovs-vsctl set-controller %s tcp:%s" % (bridge_name, contr_addr)
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", contr_addr)

            command = "sudo ovs-vsctl set-manager ptcp:6632"
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", contr_addr)

            command = "sudo ovs-vsctl set-fail-mode %s secure" % bridge_name
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", bridge_name)

            command = "sudo ovs-vsctl set controller %s connection-mode=out-of-band" % bridge_name
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", bridge_name)


        if 'int_ip' in sw_prop_map:
            int_port, int_ip = sw_prop_map["int_ip"]

            command = "sudo ovs-vsctl add-port %s %s -- set interface %s type=internal" % (bridge_name, int_port, int_port)
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", int_port)

            command =  "mac=`sudo ovs-vsctl get interface %s mac_in_use`;sudo ovs-vsctl set interface %s mac=\"$mac\"" % (int_port, int_port)
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", int_port)

            command = "sudo ifconfig %s %s/24 up" %(int_port, int_ip)
            print("## IFCONFIG: %s" %command)
            execute_and_verify(ssh, command, "ifconfig", int_ip)

        node_ip = ''# the internal ip for use in the vxlan set up
        vni = 0 #The VNI- only VMs on the VNI can communicate

        #The iterate over nodes connected to this switch

        # Add counter to properly add for switch bridges
        counter = 1
        for node in sw_topo_map:

            # Create a new ovs bridge to handle vxlan
            br_name = bridge_name+str(counter)

            # Create veth pair interfaces
            veth_pair_1 = "pair_h"+str(counter)+"_1"
            veth_pair_2 = "pair_h"+str(counter)+"_2"

            command = "sudo ip link add "+veth_pair_1+" type veth peer name "+veth_pair_2
            print("## IFCONFIG: %s" %command)
            # Atleast check if one interface is set up
            execute_and_verify(ssh, command, "ifconfig", veth_pair_1)

            # Set interfaces up
            command = "sudo ifconfig %s up" %(veth_pair_1)
            print("## IFCONFIG: %s" %command)
            execute_and_verify(ssh, command, "ifconfig", veth_pair_1)

            # Set interfaces up
            command = "sudo ifconfig %s up" %(veth_pair_2)
            print("## IFCONFIG: %s" %command)
            execute_and_verify(ssh, command, "ifconfig", veth_pair_2)

            # Create a new ovs-bridge
            command = "sudo ovs-vsctl add-br %s" % br_name
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", br_name)

            # Add veth_pair_1 to main bridge
            command = "sudo ovs-vsctl add-port %s %s" % (bridge_name, veth_pair_1)
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", veth_pair_1)

            # Add veth_pair_2 to new created bridge
            command = "sudo ovs-vsctl add-port %s %s" % (br_name, veth_pair_2)
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", veth_pair_2)

            # handle hosts
            if isinstance(node, tuple):
                vni = _get_vni(node[0], sw_name)
                node_ip = hosts_dict[node[0]]["ip_addr"]
            # handle switches
            else:
                vni = _get_vni(node, sw_name)
                node_ip = switches_dict[node]["ip_addr"]

            command = "sudo ovs-vsctl add-port %s vxlan%s -- set interface vxlan%s type=vxlan options:remote_ip=%s options:key=%s  options:dst_port=8479" % (br_name, vni, vni, node_ip, vni)
            print("## OVS-COMMAND: %s" %command)
            execute_and_verify(ssh, command, "ovs", str(vni))
            counter = counter + 1

        print("*** FINISHED SETTING UP SWITCH: %s ***" %sw_name)
        ssh.close()

def setup_hosts(hosts_dict, switches_dict):
    for host_name, host_dict in hosts_dict.items():
        #print "setting up {}".format(host_name)
        print("*** SETUP HOST: %s ***" %host_name)

        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(host_dict["ip_addr"], username=host_dict["user_name"], key_filename=config.private_key_file)
        time.sleep(3)

        # Add hostname to VM, such that it does not annoy with 'Unable to ...' error
        add_hostname(ssh)

        count = 0

        for sw_name, connections in topology.topology.items():
            for h in connections:
                if h[0] == host_name:
                    vxlan_ip = h[1]
                    bridge_name = h[2] if len(h) >= 3 else 'br%s' % count

                    # run the ovs commands
                    command = "sudo ovs-vsctl add-br %s" % bridge_name
                    print("## OVS-COMMAND: %s" %command)
                    execute_and_verify(ssh, command, "ovs", bridge_name)

                    command = "sudo ovs-vsctl add-port %s p%s -- set interface p%s type=internal" % (bridge_name,count, count)
                    print("## OVS-COMMAND: %s" %command)
                    keyword_search = "p%s" % count
                    execute_and_verify(ssh, command, "ovs", keyword_search)

                    command =  "mac=`sudo ovs-vsctl get interface p%s mac_in_use`;sudo ovs-vsctl set interface p%s mac=\"$mac\"" % (count, count)
                    print("## OVS-COMMAND: %s" %command)
                    keyword_search = "p%s" % count
                    execute_and_verify(ssh, command, "ovs", keyword_search)

                    command = "sudo ifconfig p%s %s/24 up" %(count, vxlan_ip)
                    print("## IFCONFIG: %s" %command)
                    execute_and_verify(ssh, command, "ifconfig", str(vxlan_ip))

                    command = "sudo ifconfig p%s mtu 1300" %(count)
                    print("## IFCONFIG: %s" %command)
                    execute_and_verify(ssh, command, "ifconfig", str(vxlan_ip))

                    #get switch ip addr
                    switch_ip = switches_dict[sw_name]["ip_addr"]

                    vni = _get_vni(sw_name, host_name)

                    command = "sudo ovs-vsctl add-port %s vxlan%s -- set interface vxlan%s type=vxlan options:remote_ip=%s options:key=%s options:dst_port=8479" % (bridge_name,vni,vni,switch_ip, vni)
                    print("## OVS-COMMAND: %s" %command)
                    execute_and_verify(ssh, command, "ovs", str(vni))
                    count += 1
        print("*** FINISHED SETTING UP HOST: %s ***" %host_name)
        ssh.close()

#Delete VMs that match instance prefix
def delete_vms(nova):
    for s in nova.servers.list():
        if config.instance_prefix in s.name:
            print "Deleting " + s.name
            s.delete()

#walks through the topology dict and
#'completes' the topology, i.e.
#adds the bidirectionality info in the corresponding switch
#otherwise the vxlan tunnels are only one-way
#NOTE: This only works for singly-homed hosts
def complete_topology():
    #A list view of a map of interconnections
    #{sw_n: [connections], ...} -> [('sw_n', [connections] ), ...]
    topo_list = topology.topology.items()
    #sw_tuple == ('sw_n', [connection])
    for idx, sw_tuple in enumerate(topo_list):
        #pdb.set_trace()
        #The name, and connections of this switch
        this_sw_name, this_sw_conn = sw_tuple

        #The other switches
        other_sws = topo_list[:idx] + topo_list[idx+1:]

        #Iterate over the other switches
        for other_sw, conn in other_sws:
           for sw in conn:
               sw_name = sw[0] if type(sw) == tuple else sw

               #Update this_sw_conn since this_sw
               #appears in the dict of another switch
               if sw_name == this_sw_name and other_sw not in this_sw_conn:
                    this_sw_conn.append(other_sw)

    topo_map = dict(topo_list)

if __name__ == "__main__":

    complete_topology()
    #print "EXITING"
    #sys.exit(0)

    #Create nova and quantum instance
    nova = nclient.Client(config.username, config.password, config.tenant_name, config.auth_url, region_name=config.region_name, no_cache=True)
    quantum = qclient.Client(username=config.username, password=config.password, tenant_name=config.tenant_name, auth_url=config.auth_url, region_name=config.region_name)


    #Delete any existing VMs
    delete_vms(nova)

    #List of security groups
    seclist = [config.sec_group_name]
    secgroup=nshell._get_secgroup(nova, config.sec_group_name)
    add_secrules(nova, secgroup)

    #nic
    network_resource = quantumv20.find_resourceid_by_name_or_id(quantum, 'network', config.tenant_name+'-net')
    nic = {'net-id': network_resource, 'v4-fixed-ip': None}
    nics = [nic]

    hosts = {} #map of host name to host dict
    switches = {} #map of switch name to switch dict
    for node_name, node in topology.hosts.items():
        region = node['region']
        flavor = node['flavor']
        vm_dict = create_node(node, node_name, region, flavor, nova, nics)
        vm_dict["network_id"] = network_resource
        hosts[node_name] = vm_dict

    for node_name, node in topology.switches.items():
        region = node['region']
        flavor = node['flavor']
        vm_dict = create_node(node, node_name, region, flavor, nova, nics)
        vm_dict["network_id"] = network_resource
        switches[node_name] = vm_dict

    nodes = dict(hosts.items() + switches.items()) #Joint dict of all nodes

    check_server_status(nodes) #Returns when all servers are completed
    sanity_test(nodes) #Performs ping test on newly booted vms
    setup_switches(hosts, switches)

    #config_hosts_elascale() # Configure hosts for Elascale
    setup_hosts(hosts, switches)
    pretty_print(nodes)  #Pretty table
